{{- $serviceName := .Values.serviceName }}
{{- $port := .Values.port }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi
      containers:
        - name: {{ $serviceName }}
          image: {{ .Values.image }}
          env:
            - name: TZ
              value: Europe/Copenhagen
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            {{- if eq .Values.serviceName "homepage" }}
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.pi.local" # TODO: should be part of the configuration Testing
            {{- end }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          volumeMounts:
            {{- range .Values.mountPoints }}
            - mountPath: {{ .destination | quote }}
              name: {{ $serviceName }}-{{ .name }}
              mountPropagation: HostToContainer
            {{- end }}
      volumes:
        {{- range .Values.mountPoints }}
        - name: {{ $serviceName }}-{{ .name }}
          hostPath:
            path: {{ .source | quote }}
        {{- end }}
      securityContext:
        runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
spec:
  selector:
    app: {{ $serviceName }}
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $serviceName }}
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ $serviceName }}.pi.local`)
    services:
    - kind: Service
      name: {{ $serviceName }}
      namespace: server
      port: {{ $port }}