{{- $serviceName := .Values.serviceName }}
{{- $port := .Values.port }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: rpi
      containers:
        - name: {{ $serviceName }}
          image: {{ .Values.image }}
          env:
            - name: TZ
              value: Europe/Copenhagen
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          volumeMounts:
            {{- range .Values.mountPoints }}
            - mountPath: {{ .destination | quote }}
              name: {{ $serviceName }}-{{ .name }}-claim
            {{- end }}
      volumes:
        {{- range .Values.mountPoints }}
        - name: {{ $serviceName }}-{{ .name }}-claim
          persistentVolumeClaim:
            claimName: {{ $serviceName }}-{{ .name }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
spec:
  selector:
    app: {{ $serviceName }}
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
{{- range .Values.mountPoints }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $serviceName }}
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ $serviceName }}.pi.local`)
    services:
    - kind: Service
      name: {{ $serviceName }}
      namespace: server
      port: {{ $port }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $serviceName }}-{{ .name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $serviceName }}-{{ .name }}
spec:
  storageClassName: {{ $serviceName }}-{{ .name }}
  capacity:
    storage: 100Mi # Required value, but is ignored by local-path-provisioner
  accessModes:
    - ReadWriteOnce
  local:
    path: {{ .source | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rpi
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $serviceName }}-{{ .name }}
spec:
  storageClassName: {{ $serviceName }}-{{ .name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Required value, but is ignored by local-path-provisioner
{{- end }}