{{- $serviceName := .Values.serviceName }}
{{- $port := .Values.port }}
{{- $route := .Values.route }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      containers:
        - name: {{ $serviceName }}
          image: {{ .Values.image }}
          env:
            - name: TZ
              value: Europe/Copenhagen
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          volumeMounts:
            {{- range .Values.mountPoints }}
            - mountPath: {{ .destination | quote }}
              name: {{ $serviceName }}-{{ .name }}-claim
            {{- end }}
      volumes:
        {{- range .Values.mountPoints }}
        - name: {{ $serviceName }}-{{ .name }}-claim
          persistentVolumeClaim:
            claimName: {{ $serviceName }}-{{ .name }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
spec:
  selector:
    app: {{ $serviceName }}
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
{{- range .Values.mountPoints }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
spec:
  rules:
  - host: "pi.local"
    http:
      paths:
      - path: {{ $route | quote }}
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $port }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $serviceName }}-{{ .name }}
provisioner: rancher.io/local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $serviceName }}-{{ .name }}
spec:
  storageClassName: {{ $serviceName }}-{{ .name }}
  capacity:
    storage: 100Mi # Required value, but is ignored by local-path-provisioner
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .source | quote }}
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $serviceName }}-{{ .name }}
spec:
  storageClassName: {{ $serviceName }}-{{ .name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # Required value, but is ignored by local-path-provisioner
{{- end }}