services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - "/home/x42/PP/MediaServer/config/jellyfin:/config:z"
      - "/home/x42/PP/MediaServer/cache/jellyfin:/cache:z"
      - type: bind
        source: "/home/x42/PP/MediaServer/media/movies"
        target: "/media/movies"
      - type: bind
        source: "/home/x42/PP/MediaServer/media/tv"
        target: "/media/tv"
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - "/home/x42/PP/MediaServer/config/prowlarr:/config:z"

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
    volumes:
      - "/home/x42/PP/MediaServer/config/qbittorrent:/config:z"
      - "/home/x42/PP/MediaServer/media/movies:/downloads:z"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "gethomepage.dev" # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    volumes:
      - type: bind
        source: "/home/x42/PP/MediaServer/dev/services.yaml"
        target: "/app/config/services.yaml"
      - "/home/x42/PP/MediaServer/config/homepage:/app/config:z"
    
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    volumes:
      - "/home/x42/PP/MediaServer/config/flaresolverr:/config:z"