- MediaServer:
    - qBittorrent:
        icon: https://a.fsdn.com/allura/p/qbittorrent/icon?1724097660?&w=90
        href: http://localhost:8080/
    - Prowlarr:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/prowlarr.png
        href: http://localhost:9696/
    - Jellyfin:
        icon: https://images.icon-icons.com/3912/PNG/512/jellyfin_logo_icon_247973.png
        href: http://localhost:8096/