services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    volumes:
      - /provision/jellyfin/config:/config
      - /provision/jellyfin/cache:/cache
      - type: bind
        source: /Volumes/T5/MediaServer/media
        target: /media
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - /provision/qbittorrent/config:/config
      - /Volumes/T5/MediaServer/media/movies:/data/torrents
    ports:
      - "8080:8080"
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - /provision/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
