apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-ingress
  annotations:
    nxginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            servicePort: 80