---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`argocd.pi.local`)
    middlewares:
      - name: redirect-http-https
    services:
    - kind: Service
      name: argocd-server
      namespace: argocd
      port: 443
