- Download:
    - Prowlarr:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/prowlarr.png
        href: ${PROWLARR_URL}
    - qBittorrent:
        icon: https://a.fsdn.com/allura/p/qbittorrent/icon?1724097660?&w=90
        href: ${QBITTORRENT_URL}
- Watch:
    - Jellyfin:
        icon: https://images.icon-icons.com/3912/PNG/512/jellyfin_logo_icon_247973.png
        href: ${JELLYFIN_URL}