#!/usr/bin/env bash

set -e
set -u
set -o pipefail


if [ $# -eq 0 ] || { [ "$1" != "run" ] && [ "$1" != "test" ]; }; then
    echo "Usage: $0 [run|test]"
    exit 1
fi

echo "- Loading environment variables from .env file..."
ENVFILE="$(dirname "${BASH_SOURCE[0]}")/.env"
if [ -f "$ENVFILE" ]; then
    set -a
    source "$ENVFILE"
    set +a
else
    echo "- .env file not found. Skipping loading environment variables."
fi

CURRENT_DIR="$(dirname "${BASH_SOURCE[0]}")"
if [ "$1" = "run" ]; then
    echo "- Running configuration services..."
    echo ""
    go run "$CURRENT_DIR"/main.go
elif [ "$1" = "test" ]; then
    echo "- Running tests..."
    echo ""
    go test "$CURRENT_DIR/..."
fi