apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mediaserver-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  generators:
    - git:
      repoURL: https://github.com/Cupprum/MediaServer.git
      files:
        - path: "server/service-chart/values/*.yaml"
  template:
    metadata:
      name: '{{path.basenameNormalized}}-app'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      source:
        repoURL: https://github.com/Cupprum/MediaServer.git
        path: server/service-chart
        helm:
          valueFiles:
            - values/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: server
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true