apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mediaserver-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Cupprum/MediaServer.git
        revision: HEAD
        files:
          - path: "server/service-chart/values/*.yaml"
  template:
    metadata:
      name: '{{ .path.filename | trimSuffix ".yaml" }}-app'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: default
      source:
        repoURL: https://github.com/Cupprum/MediaServer.git
        targetRevision: HEAD
        path: server/service-chart
        helm:
          valueFiles:
            - values/{{ .path.filename }}
      destination:
        server: https://kubernetes.default.svc
        namespace: server
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true