apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:latest
          env:
            - name: TZ
              value: Europe/Copenhagen
          ports:
            - containerPort: 9696
              hostPort: 9696
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: prowlarr-claim
      volumes:
        - name: prowlarr-claim
          persistentVolumeClaim:
            claimName: prowlarr
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  ports:
    - name: "9696"
      port: 9696
      targetPort: 9696
  selector:
    app: prowlarr
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prowlarr
provisioner: rancher.io/local-path
# volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr
spec:
  storageClassName: prowlarr
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Volumes/T5/MediaServer/provision/prowlarr/config"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
spec:
  storageClassName: prowlarr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi