apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: TZ
              value: Europe/Copenhagen
          ports:
            - containerPort: 8080 # NOTE: previously i also provided 443
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-config-claim
            - mountPath: /data/torrents
              name: qbittorrent-data-claim
      volumes:
        - name: qbittorrent-config-claim
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: qbittorrent-data-claim
          persistentVolumeClaim:
            claimName: qbittorrent-data
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: qbittorrent
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qbittorrent-config
provisioner: rancher.io/local-path
# volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config
spec:
  storageClassName: qbittorrent
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Volumes/T5/MediaServer/provision/qbittorrent/config"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
spec:
  storageClassName: qbittorrent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qbittorrent-data
provisioner: rancher.io/local-path
# volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-data
spec:
  storageClassName: qbittorrent
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Volumes/T5/MediaServer/media/movies"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
spec:
  storageClassName: qbittorrent
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi