apps:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    port: 8080
    healthcheck: /
    mountPoints:
      - name: data
        source: /media/x42/T5/media
        destination: /config/Downloads
  prowlarr:
    image: linuxserver/prowlarr:latest
    port: 9696
    healthcheck: /ping
  jellyfin:
    image: jellyfin/jellyfin:10.10
    port: 8096
    healthcheck: /health
    mountPoints:
      - name: data
        source: /media/x42/T5/media
        destination: /media
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    port: 8191
    healthcheck: /
config:
  plain:
    MEDIASERVER_JELLYFIN_DEPLOY: "true"
    MEDIASERVER_JELLYFIN_URL: "http://localhost:8096"
    MEDIASERVER_JELLYFIN_OPENSUBTITLES_ENABLED: "true"
    MEDIASERVER_QBITTORRENT_DEPLOY: "true"
    MEDIASERVER_QBITTORRENT_URL: "http://qbittorrent:8080"
    MEDIASERVER_QBITTORRENT_HOSTNAME: "qbittorrent"
    MEDIASERVER_PROWLARR_DEPLOY: "true"
    MEDIASERVER_PROWLARR_URL: "http://prowlarr:9696"
    MEDIASERVER_PROWLARR_1337X_ENABLED: "true"
    MEDIASERVER_PROWLARR_EZTV_ENABLED: "true"
    MEDIASERVER_PROWLARR_INTERNETARCHIVE_ENABLED: "true"
    MEDIASERVER_PROWLARR_LIMETORRENTS_ENABLED: "true"
    MEDIASERVER_PROWLARR_PIRATEBAY_ENABLED: "false"
    MEDIASERVER_PROWLARR_YTS_ENABLED: "true"
    MEDIASERVER_PROWLARR_RUTRACKER_ENABLED: "true"
    MEDIASERVER_PROWLARR_SKTORRENT_ENABLED: "true"
    MEDIASERVER_PROWLARR_SKCZTORRENT_ENABLED: "true"
    MEDIASERVER_FLARESOLVERR_HOST_URL: "http://flaresolverr:8191"
  secrets:
    MEDIASERVER_JELLYFIN_USERNAME: jellyfin-username
    MEDIASERVER_JELLYFIN_PASSWORD: jellyfin-password
    MEDIASERVER_JELLYFIN_OPENSUBTITLES_USERNAME: jellyfin-opensubtitles-username
    MEDIASERVER_JELLYFIN_OPENSUBTITLES_PASSWORD: jellyfin-opensubtitles-password
    MEDIASERVER_QBITTORRENT_USERNAME: qbittorrent-username
    MEDIASERVER_QBITTORRENT_PASSWORD: qbittorrent-password
    MEDIASERVER_QBITTORRENT_RAW_PASSWORD: qbittorrent-raw-password
    MEDIASERVER_PROWLARR_USERNAME: prowlarr-username
    MEDIASERVER_PROWLARR_PASSWORD: prowlarr-password
    MEDIASERVER_PROWLARR_RUTRACKER_USERNAME: prowlarr-rutracker-username
    MEDIASERVER_PROWLARR_RUTRACKER_PASSWORD: prowlarr-rutracker-password
    MEDIASERVER_PROWLARR_SKTORRENT_USERNAME: prowlarr-sktorrent-username
    MEDIASERVER_PROWLARR_SKTORRENT_PASSWORD: prowlarr-sktorrent-password
    MEDIASERVER_PROWLARR_SKCZTORRENT_USERNAME: prowlarr-skcztorrent-username
    MEDIASERVER_PROWLARR_SKCZTORRENT_PASSWORD: prowlarr-skcztorrent-password