storage:
  source: /media/x42/T5/MediaServer/provision/prometheus

prometheus:
  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  server:
    persistentVolume:
      existingClaim: prometheus

    securityContext:
      runAsUser: 1000
      runAsNonRoot: false
      runAsGroup: 1000
      fsGroup: 1000

    service:
      servicePort: 9090

    serverFiles:
      prometheus.yml:
        global:
          scrape_interval: 15s

        scrape_configs:
          - job_name: prometheus
            static_configs:
              - targets: ['localhost:9090']

          - job_name: node
            static_configs:
              - targets: ['localhost:9100']

  configmapReload:
    prometheus:
      enabled: false

grafana:
  admin:
    existingSecret: "grafana-admin-credentials"
  service:
    enabled: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server.monitoring.svc.cluster.local:9090
          access: proxy
          isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      node-exporter-full:
        gnetId: 1860
        revision: 41
        datasource: Prometheus

      kubernetes-cluster-monitoring-via-prometheus:
        gnetId: 19105
        revision: 7
        datasource: Prometheus

  ingress:
    enabled: true
    hosts:
      - "grafana.pi.local"
    path: /