storage:
  source: /media/x42/T5/MediaServer/provision/prometheus

prometheus:
  alertmanager:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  server:
    persistentVolume:
      existingClaim: prometheus

    securityContext:
      runAsUser: 1000
      runAsNonRoot: false
      runAsGroup: 1000
      fsGroup: 1000

    service:
      servicePort: 9090

  configmapReload:
    prometheus:
      enabled: false

grafana:
  service:
    enabled: true
    type: NodePort
    port: 3000