apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediaserver-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/Cupprum/MediaServer.git
    path: kube/service-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true